### ISSUE TITLE
Using :git => repo_path when there is a gem floating around will ignore the :git repo

### ISSUE THREAD

**Issue by jweiss** [wycats/bundler#100]
I have the following in my Gemfile:

source "http://gemcutter.org"
gem 'nanite', nil, :git => "git://github.com/peritor/nanite"

A `gem bundle` will result in bundler installing the nanite gem from gemcutter and not using my git repository. A `gem bundle --cached` works BTW. 

This is on a Rails 2.3.4 app configured from Yehuda's blog post.

**Comment by carllerche** [comment]
This should be fixed on mastedr
