### ISSUE TITLE
Should we add bin/* to gitignore?

### ISSUE THREAD

**Issue by trevorturk** [wycats/bundler#101]
When running "gem bundle" I have files show up in bin/ - I think the correct thing to do is to add "bin/*" to my gitignore. Does that sound right?

As an aside, I think that having an example of what to .gitignore in the bundler README would be a nice touch. I had to use your blog post on the bundler to figure it out. 

Thanks!

**Comment by carllerche** [comment]
bin/\* should be added to .gitignore.

I updated the example in the README.

**Comment by trevorturk** [comment]
Awesome - thank you!
