### ISSUE TITLE
Problem with version numbers like "0.6.rc1"

### ISSUE THREAD

**Issue by jweiss** [wycats/bundler#105]
Webrat master currently has "0.6.rc1" as the version string in the gemspec.

Bundler does not recognize this when I use webrat in a :git definition.:

% gem bundle
Calculating dependencies...
Updating source: http://gemcutter.org
Updating source: http://gems.rubyforge.org
Could not find gem 'webrat (>= 0, runtime)' in any of the sources

When I manually change the "0.6.rc1" to "0.6" in Webrat's gemspec, everything is fine again.

**Comment by wycats** [comment]
We don't automatically use prerelease gems unless you explicitly specify them (same semantics as Rubygems itself). To make this work, do:

gem "webrat", "0.6.rc1", ...

**Comment by carllerche** [comment]
Please show me your Gemfile. I might be able to add some sugar for this, but you can do gem "webrat", "0.6.rc1", :git => "..." and it should work.

**Comment by jweiss** [comment]
This is the gem file:

---

bundle_path "vendor/bundler_gems"
source "http://gemcutter.org"
gem "rack", ">=1.0.1"
gem "rails", "2.3.4"
gem 'right_aws', '1.10.0', :git => "git://github.com/peritor/right_aws"
gem 'amqp', nil, :git => "git://github.com/peritor/amqp"
gem 'nanite', nil, :git => "git://github.com/peritor/nanite"
gem 'deep_merge', '0.1.1', :git => "git://github.com/peritor/deep_merge"

gem "uuidtools"
gem "validatable"
gem "mime-types", nil, :require_as => 'mime/types'
gem 'rest-client', nil, :require_as => 'restclient'
gem 'couchrest'
gem 'redis', nil, :git => "git://github.com/ezmobius/redis-rb", :shallow => true

only :test do
  gem 'webrat', nil, :git => "git://github.com/jweiss/webrat" 
  gem 'shoulda' 
  gem 'mocha' 
  gem 'random_data' 
  gem 'shoulda-addons', :lib => 'shoulda_benchmark' 
  gem 'moqueue' 
end

---

I understand skipping pre-release gems by default but if I specify the :git repository I would expect Bundler to pick what ever version it has.

Thanks,
Jonathan

**Comment by carlhuda** [comment]
This has been fixed on master.
