### ISSUE TITLE
Failed native gem install isn't retried

### ISSUE THREAD

**Issue by jeremy** [wycats/bundler#106]
To reproduce, bundle a native gem whose compile will fail. Gives an error message. Now gem bundle again. The compile isn't attempted again, leaving a broken environment.

**Comment by jeremy** [comment]
Workaround is to rm -rf vendor/gems/gems/badgem-1.2.3

**Comment by richievos** [comment]
+1 Got burned by this with mysql.

**Comment by 3lsilver** [comment]
I am getting burned by this as well.  I am also having to delete the bad gems.

**Comment by carlhuda** [comment]
Cleanup after geminstalls that don't finish because of errors. Closed by 3f926f0dfce2675d5d1c936869b20a106ce07285.

**Comment by carlhuda** [comment]
Fixed.
