### ISSUE TITLE
Gem updating without changes to Gemfile with specific versions for every gem

### ISSUE THREAD

**Issue by joefiorini** [wycats/bundler#109]
Our Gemfile has specific versions setup for every gem. However, one of our developers ran "gem bundle" today and bundler updated json_pure to 1.2.0 (it was released 11/7 after we had setup bundler). json_pure is not a direct dependency in our application (not specified in Gemfile) and I was unable to ascertain which gem depends on it. For now we have added json_pure to Gemfile at 1.2.0. Seems like a bug that bundler doesn't freeze dependencies by version.

**Comment by joefiorini** [comment]
I am aware that this may not be a bug, but the google group is so full of spam I don't want to join it. If it's not a bug, feel free to close the issue; I would appreciate any information on solving our problem though. Could be my own misunderstanding. Thanks!

**Comment by carlhuda** [comment]
This will be resolved by having gem bundle emit a YAML file with the SHA of the Gemfile and the fully resolved contents. If the Gemfile is changed, a new resolve will take place. Otherwise, we will always use the resolution results that were in the YAML with gem bundle (unless you do --update)
