### ISSUE TITLE
warning: instance variable `XXX` not initialized

### ISSUE THREAD

**Issue by bkaney** [wycats/bundler#112]
I've installed bundler for use with a rails 2.3.4 app (I am using rspec, although I don't think it is related).

If I run `rake --trace`, I see a bunch of warning messages about uninitialized instance and global variables.  Not sure if the gem's init.rb is being loaded.  Or maybe there is a way to suppress these warnings that I'm not aware of...

**Comment by bkaney** [comment]
Here's a tiny part of my `rake --trace` output.  It seems to happen right after it loads the environment:
    $ rake --trace
    (in /Users/bkaney/Projects/ric/babelscrip)
    *\* Invoke default (first_time)
    *\* Invoke spec (first_time)
    *\* Invoke db:test:prepare (first_time)
    *\* Invoke db:abort_if_pending_migrations (first_time)
    *\* Invoke environment (first_time)
    *\* Execute environment
    /Users/bkaney/Projects/ric/babelscrip/vendor/bundler_gems/gems/rails-2.3.4/lib/initializer.rb:778: warning: instance variable @reload_plugins not initialized
    ..many more follow..

**Comment by bkaney** [comment]
Closing my own ticket.  The issue appears to be with vlad...

**Comment by carlhuda** [comment]
Thanks.
