### ISSUE TITLE
Bundler seems to fail at bundling JRuby gem versions

### ISSUE THREAD

**Issue by rubiii** [wycats/bundler#113]
Hi,

I noticed that with Hpricot 0.8.2 (which is available for both MRI and JRuby), running "gem bundle" with JRuby does not resolve the JRuby version of the gem. It just goes for the MRI version which fails due to native extensions.

```
jruby -S gem install hpricot --version 0.8.2
```

Installs the JRuby version, so I expected bundler to bundle the JRuby version as well.

Can anyone verify or recommend a fix?

**Comment by MSch** [comment]
I can verify this bug.
I use
    gem 'hpricot', :bundle => false
and install hpricot via the old "gem install hpricot" way
