### ISSUE TITLE
~> in version string stopped working

### ISSUE THREAD

**Issue by paul** [wycats/bundler#114]
This used to work, in bundler < 0.6.0 (?) 

Gemfile:
    gem "rack-mount",   "~> 0.0.1", :git => "git://github.com/rails/rack-mount.git"

From latest pull of bundler, I get:

% gem bundle --backtrace
ERROR:  While executing gem ... (ArgumentError)
    Malformed version number string ~> 0.0.1
        /home/rando/.rvm/ruby-1.8.7-p174/lib/ruby/site_ruby/1.8/rubygems/version.rb:107:in `initialize'
        /home/rando/.rvm/gems/ruby/1.8.7/gems/bundler-0.7.0/lib/bundler/source.rb:189:in`new'
        /home/rando/.rvm/gems/ruby/1.8.7/gems/bundler-0.7.0/lib/bundler/source.rb:189:in `add_spec'
        /home/rando/.rvm/ruby-1.8.7-p174/lib/ruby/site_ruby/1.8/rubygems/specification.rb:421:in`initialize'
        /home/rando/.rvm/gems/ruby/1.8.7/gems/bundler-0.7.0/lib/bundler/source.rb:187:in `new'
        /home/rando/.rvm/gems/ruby/1.8.7/gems/bundler-0.7.0/lib/bundler/source.rb:187:in`add_spec'
        /home/rando/.rvm/gems/ruby/1.8.7/gems/bundler-0.7.0/lib/bundler/dsl.rb:150:in `_handle_git_option'
        /home/rando/.rvm/gems/ruby/1.8.7/gems/bundler-0.7.0/lib/bundler/dsl.rb:154:in`_handle_git_option'
        /home/rando/.rvm/gems/ruby/1.8.7/gems/bundler-0.7.0/lib/bundler/dsl.rb:71:in `git'
        /home/rando/.rvm/gems/ruby/1.8.7/gems/bundler-0.7.0/lib/bundler/dsl.rb:153:in`_handle_git_option'
        /home/rando/.rvm/gems/ruby/1.8.7/gems/bundler-0.7.0/lib/bundler/dsl.rb:97:in `gem'
        /home/rando/development/api/escdef/Gemfile:7:in`evaluate'
        /home/rando/.rvm/gems/ruby/1.8.7/gems/bundler-0.7.0/lib/bundler/environment.rb:45:in `initialize'
        /home/rando/.rvm/gems/ruby/1.8.7/gems/bundler-0.7.0/lib/bundler/environment.rb:20:in`new'
        /home/rando/.rvm/gems/ruby/1.8.7/gems/bundler-0.7.0/lib/bundler/environment.rb:20:in `load'
        /home/rando/.rvm/gems/ruby/1.8.7/gems/bundler-0.7.0/lib/bundler/cli.rb:35:in`initialize'
        /home/rando/.rvm/gems/ruby/1.8.7/gems/bundler-0.7.0/lib/bundler/cli.rb:6:in `new'
        /home/rando/.rvm/gems/ruby/1.8.7/gems/bundler-0.7.0/lib/bundler/cli.rb:6:in`run'
        /home/rando/.rvm/gems/ruby/1.8.7/gems/bundler-0.7.0/lib/bundler/commands/bundle_command.rb:68:in `execute'
        /home/rando/.rvm/ruby-1.8.7-p174/lib/ruby/site_ruby/1.8/rubygems/command.rb:257:in`invoke'
        /home/rando/.rvm/ruby-1.8.7-p174/lib/ruby/site_ruby/1.8/rubygems/command_manager.rb:132:in `process_args'
        /home/rando/.rvm/ruby-1.8.7-p174/lib/ruby/site_ruby/1.8/rubygems/command_manager.rb:102:in`run'
        /home/rando/.rvm/ruby-1.8.7-p174/lib/ruby/site_ruby/1.8/rubygems/gem_runner.rb:58:in `run'
        /home/rando/.rvm/ruby-1.8.7-p174/bin/gem:21

**Comment by carlhuda** [comment]
Bring back ryan davis spermy operators for git & directory sources. Closed by 327af9c55c8dbf9b3e0ee280446d083a3279b393
