### ISSUE TITLE
gem loading order

### ISSUE THREAD

**Issue by agibralter** [wycats/bundler#118]
I noticed a problem that comes up with some gems such as after_commit. I posted a gist here with the details: https://gist.github.com/039d9e5ce54f4a11ce70. It seems like some gems when loaded assume that Rails has already been loaded... in the case of after_commit it tries to include a module in all the subclasses of ActiveRecord::ConnectionAdapters::AbstractAdapter; however, since gem bundler loads the after_commit.rb library before Rails has figured out which subclasses of AbstractAdapter to initialize (MysqlAdapter in my case), the module is not included and breaks my app.

I can't figure out if this is a problem with gem bundler for changing gem load order... or a problem with a bunch of gems out there that /assume/ a certain load order. In any case it seems like the community needs to agree on how to go about Rails gem development.

**Comment by agibralter** [comment]
Ok... so I changed the preinitializer hack to http://gist.github.com/242240 ... now the problems associated with gems assuming the load order associated with config.gem go away.

**Comment by carlhuda** [comment]
This is a good improvement to the README

**Comment by manuelmorales** [comment]
It seems that I'm getting a loading order problem too. Looks like calendar_date_select and faker gems require Rails to be loaded first:

/home/manuel/scrum/teamtrick/vendor/bundler_gems/gems/calendar_date_select-1.15/lib/calendar_date_select.rb:6:NameError: uninitialized constant ActionView::Helpers::FormHelper

However, the Aaron Gibralter fix (http://gist.github.com/242240/) didn't work for me. 

Any clue?

**Comment by agibralter** [comment]
Does calendar_date_select work with the config.gem method? If so, what does your line look like in environment.rb?

**Comment by manuelmorales** [comment]
Thanks for answering Aaron. My environment.rb looked like this:

```
RAILS_GEM_VERSION = '2.3.5' unless defined? RAILS_GEM_VERSION
require File.join(File.dirname(__FILE__), 'boot')
Rails::Initializer.run do |config|
  config.gem 'calendar_date_select'
  config.gem "faker"
  config.gem "populator"
  ...
```

I deleted the config.gem entries and moved them to the Gemfile like this:

```
bundle_path "vendor/bundler_gems"
disable_system_gems
gem 'rails', '2.3.5'
gem "sqlite3-ruby", :require_as => 'sqlite3'
gem "calendar_date_select"
gem "faker"
gem "populator"
...
```

And now, both gems, calendar_date_select and populator, are throwing errors because they miss Rails.

**Comment by agibralter** [comment]
Does your preinitializer.rb look like this: http://gist.github.com/242240/ ?

Are you using passenger? When do you get the NameError you pasted above?

**Comment by manuelmorales** [comment]
`preinitializer.rb` looks exactly like that. I get that error when I run `script/console`. And a similar error when running `rake db:migrate` or `script/server`. I'm not using passenger.

**Comment by agibralter** [comment]
By any chance, do you have a vendor/rails directory? If Rails's boot.rb sees the directory (even if it's empty), it will attempt a VendorBoot rather than a GemBook. I switched from using a vendor-Rails system to gem bundler and had a similar problem.

**Comment by manuelmorales** [comment]
nope, all I got inside vendor are the following directories: bundler_gems, curvycorners,  originals and  plugins.

: (

**Comment by agibralter** [comment]
The best thing that I can recommend for this sort of thing is to put:

<pre>
require 'ruby-debug'
debugger
</pre>

at the beginning of boot.rb's boot! method. Step through the boot process and try to figure out when things are getting loaded. Maybe there's a problem with order... You may have to get rid of `disable_system_gems` for the time being so that you can use `ruby-debug`. It's entirely possible that the gem is not designed too well in terms of its load-order assumptions. But you won't be able to figure that out for sure unless you step through...

**Comment by manuelmorales** [comment]
Ok, I'll take a look at that. I'll write here if I find the solution. Thanks for your time Aaron.

**Comment by agibralter** [comment]
no problem -- good luck!

**Comment by manuelmorales** [comment]
Hi! I took a look and couldn't find a solution. I decided to use gems:unpack. :(

**Comment by schlick** [comment]
I had a similar problem with bundling fakefs

```
/Users/michaelm/experiments/fakefs/vendor/bundler_gems/ruby/1.8/gems/fakefs-0.2.1/lib/fakefs/file.rb:260:in
 `check_file_existence!':Errno::ENOENT: No such file or directory - 
No such file or directory - 
/opt/local/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:443:in 
`load_missing_constant':NameError: uninitialized constant ApplicationController
```

In the end I simply installed it as a plugin.

**Comment by ccthiel** [comment]
I've had the same problem with factory_girl:
`c:/code/test_harness/vendor/woot/gems/railties-3.0.0.beta/lib/rails.rb:40:in 'configuration': undefined method 'config' for nil:NilClass (NoMethodError)
        from c:/code/test_harness/vendor/woot/gems/factory_girl-1.2.3/lib/factory_girl.rb:25:in '<top (required)>'
        from c:/code/test_harness/vendor/woot/gems/bundler-0.9.9/lib/bundler/runtime.rb:41:in 'require'
        from c:/code/test_harness/vendor/woot/gems/bundler-0.9.9/lib/bundler/runtime.rb:41:in 'block (2 levels) in require'
        from c:/code/test_harness/vendor/woot/gems/bundler-0.9.9/lib/bundler/runtime.rb:36:in 'each'
        from c:/code/test_harness/vendor/woot/gems/bundler-0.9.9/lib/bundler/runtime.rb:36:in 'block in require'
        from c:/code/test_harness/vendor/woot/gems/bundler-0.9.9/lib/bundler/runtime.rb:35:in 'each'
        from c:/code/test_harness/vendor/woot/gems/bundler-0.9.9/lib/bundler/runtime.rb:35:in 'require'
        from c:/code/test_harness/vendor/woot/gems/bundler-0.9.9/lib/bundler.rb:71:in 'require'
        from c:/code/test_harness/config/application.rb:6:in '<top (required)>'
        from c:/code/test_harness/config/environment.rb:2:in 'require'
        from c:/code/test_harness/config/environment.rb:2:in '<top (required)>'
        from c:/code/test_harness/test/test_helper.rb:2:in 'require'
        from c:/code/test_harness/test/test_helper.rb:2:in '<top (required)>'
        from c:/code/test_harness/test/unit/additional_interest_test.rb:1:in 'require'
        from c:/code/test_harness/test/unit/additional_interest_test.rb:1:in '<top (required)>'
        from c:/code/test_harness/vendor/woot/gems/rake-0.8.7/lib/rake/rake_test_loader.rb:5:in 'load'
        from c:/code/test_harness/vendor/woot/gems/rake-0.8.7/lib/rake/rake_test_loader.rb:5:in 'block in <main>'
        from c:/code/test_harness/vendor/woot/gems/rake-0.8.7/lib/rake/rake_test_loader.rb:5:in 'each'
        from c:/code/test_harness/vendor/woot/gems/rake-0.8.7/lib/rake/rake_test_loader.rb:5:in '<main>'`
