### ISSUE TITLE
Platform dependend path separator

### ISSUE THREAD

**Issue by valodzka** [wycats/bundler#120]
Bundler doesn't use platform-independent path separator and this causes invalid PATH variable at least on windows.

bundler / lib / bundler / templates / environment.erb, line 10 instead of

```
  ENV["PATH"]     = "#{dir}/<%= bindir %>:#{ENV["PATH"]}"
```

should be

```
 ENV["PATH"]     = "#{dir}/<%= bindir %>#{File::PATH_SEPARATOR}#{ENV["PATH"]}"
```

And same for enviroment.rb

**Comment by carlhuda** [comment]
Use platform-independent path-separator. Closed by d7941860b9cfd6087b0e97eea01e9ddb5b44b895
