### ISSUE TITLE
"gem bundle" updates outdated gems

### ISSUE THREAD

**Issue by stefanpenner** [wycats/bundler#121]
as per http://yehudakatz.com/2009/11/03/using-the-new-gem-bundler-today/
"Bundler conservatively does not update your gems simply because a new version came out that satisfies the requirement. This is so that you can be sure that the versions running on your local machine will make it safely to production. This will allow you to check for outdated gems so you can decide whether to update your gems with –update."

it seems gem bundle does trigger updating gem outdated gems

example
1. Inside Gemfile: gem "somegem", "oldversion"
2. gem bundle
3. Inside Gemfile: gem "somegone" ( remove the version declaration )
4. gem bundle
this results in an aggressive gem update, which seems to go against what was mentioned in the blog post, and as such seems to be a bug.

**Comment by vandrijevik** [comment]
Stefan,

Above, in step 3 you modify the requirement (such that it matches the latest available version). As such, running gem bundle finds the gem version that matches your Gemfile, and updates the one in the local repository.

Bundler won't update your gems in cases where a new version of the gem becomes available after the initial run of `gem bundle` _without you changing the Gemfile_.

**Comment by stefanpenner** [comment]
vandrijevik, nice! I should have tested it with an actual gem version update. I merely tried to simulate such an event (by changing the requirements). I suppose I did not give the bundler enough credit. No bug, translates into good news.

**Comment by carlhuda** [comment]
This will be resolved by having gem bundle emit a YAML file with the SHA of the Gemfile and the fully resolved contents. If the Gemfile is changed, a new resolve will take place. Otherwise, we will always use the resolution results that were in the YAML with gem bundle (unless you do --update)
