### ISSUE TITLE
Documentation for --prune-cache is incorrect

### ISSUE THREAD

**Issue by vandrijevik** [wycats/bundler#124]
The current documentation for the --prune-cache command reads:

```
"Removes all .gem files from the bundle's cache"
```

However, Repository#prune has a guard that only removes a .gem file unless the spec is a part of the bundle. Since I believe this is the correct behavior, I propose updating the documentation to:

```
"Removes all .gem files that are not a part of the bundle from the cache"
```

which accurately describes the behavior.

To make this dead-simple I've created a patch that should trivially apply, located at http://github.com/vandrijevik/bundler/commit/32f9b79a936b28f1c8b7d616aa28074103e734f9

**Comment by carlhuda** [comment]
merged, thanks for the patch
