### ISSUE TITLE
support :version as a hash parameter

### ISSUE THREAD

**Issue by richievos** [wycats/bundler#127]
It would be nice if bundler supported version as both a normal argument and as a hash parameter (ala the Rails gem manager). This is more of a convenience thing / personal preference, but the old rails manager supported this, and it'll simplify porting rails apps over.

My other concern is that if you pass :version nothing blows up, it's just silently ignored.

I sent a pull-request that I haven't heard anything back on awhile ago, but I've implemented this with a test at http://github.com/jerryvos/bundler/commit/ceb5f41985f2d76ff70c0368168213d25bdfbd12

**Comment by richievos** [comment]
Btw, the test is in the commit before that one, all on this branch: http://github.com/jerryvos/bundler/commits/version_as_hash

**Comment by jbarnette** [comment]
Don't do this. Having version be the optional second argument matches nicely with RubyGems' "gem" method, and porting from :version keys is easy (and only happens once). There's no reason to have two different ways to do it.

**Comment by richievos** [comment]
If this doesn't get done, :version => something needs to raise an error. In other words, def gem needs to validate its arguments.

**Comment by richievos** [comment]
Actually, either way that needs to happen, to make it simpler to catch yourself using the api wrong. I'll put a separate ticket in for that.

**Comment by jbarnette** [comment]
Absolutely.

**Comment by richievos** [comment]
I'm assuming from http://github.com/wycats/bundler/commit/7169d0487c61072d044029503390d1bc56b1d93d this will not be supported. Feel free to close.
