### ISSUE TITLE
DSL should validate arguments passed to gem

### ISSUE THREAD

**Issue by richievos** [wycats/bundler#128]
When calling gem in the Gemfile, there is no validation of what arguments are being passed in. This is especially bad when migrating from an existing rails config.gem set of dependencies.

For instance, the following issues can happen (and burned me):
- :version isn't respected when passed in
- :source when passed in leaves the dependencies in a screwed up state

If someone would direct me to where I might determine the full set of valid options I would happily write this, otherwise I'll try and put something together based on the readme.

**Comment by carlhuda** [comment]
done on master

**Comment by richievos** [comment]
Awesome! thanks.

Wow, my previous message got somewhat mangled, sorry about that.
