### ISSUE TITLE
Bundler is incompatible with Ruby older than 1.8.7

### ISSUE THREAD

**Issue by carlhuda** [wycats/bundler#134]
Due to use of Symbol#to_proc: keys = %w(vendored_at path only except git path bundle require_as tag branch ref).map(&:to_sym)

dsl.rb:85

**Comment by mislav** [comment]
It **must** have taken you more to open this ticket than to change the line in question :/

**Comment by carllerche** [comment]
The ticket is also to remind us to do a full sweep for any other incompatibilities ;) that, and i'm lazy

**Comment by gabrielmansour** [comment]
I sent a pull request this morning for a patch that resolves this issue.
