### ISSUE TITLE
Chokes on merb gem version "1.1.0.pre" in ruby 1.8.7

### ISSUE THREAD

**Issue by somebee** [wycats/bundler#136]
When declaring this in Gemfile:

gem 'merb-core', '1.1.0.pre'

Throws following error when loading environment in ruby 1.8.7 (works in 1.9.1). Both have latest rubygems installed.

ArgumentError /usr/local/lib/site_ruby/1.8/rubygems/version.rb:53:in `initialize': Malformed version number string 1.1.0.pre

/usr/local/lib/site_ruby/1.8/rubygems/version.rb    44  in `new'
/usr/local/lib/site_ruby/1.8/rubygems/version.rb    44  in`create'
/usr/local/lib/site_ruby/1.8/rubygems/specification.rb  1130    in `version='
(eval)  5   
/usr/local/lib/site_ruby/1.8/rubygems/specification.rb  443 in`initialize'
(eval)  3   in `new'
(eval)  3   
/usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb 31  in`eval'
./gems/environment.rb   159

**Comment by wycats** [comment]
This is fixed on master
