### ISSUE TITLE
I want to have do_postgres in production, but not have to install it in development

### ISSUE THREAD

**Issue by halorgium** [wycats/bundler#16]
Is this actually a good idea?

**Comment by atmos** [comment]
I would say it's not a big deal for now.

**Comment by wycats** [comment]
Could you please explain what you mean?

**Comment by halorgium** [comment]
One of our projects has do_postgres and do_sqlite3, but only uses do_postgres in production. 
Someone mentioned it would be useful to have this behaviour to avoid having postgresql required in development. 
I think it is bad practice now.

**Comment by wycats** [comment]
This is the same as environments
