### ISSUE TITLE
Using cached gem doesn't work anymore...

### ISSUE THREAD

**Issue by lardawge** [wycats/bundler#178]
Not sure when it changed (haven't looked that hard) but the update to 0.8.1 broke the ability to put a gem file in cache directory and use that. In my case I have modifications to a gem that I don't want to go public with and am using it in a project. When I bundle, it says it can't find it in the repository... Um, it's in cache!? If I revert to bundler 0.7.0 it works as expected.

**Comment by paukul** [comment]
did you notice that the directory structure changed?
the old vendor/gems/cache can now be found in vendor/gems/<ruby>/<version>/cache.
Which means if you put your gem in vendor/gems/cache with bundler 0.8.1, it won't find it

**Comment by lardawge** [comment]
No, I didn't notice that. Thank you for pointing that out. Problem solved.
