### ISSUE TITLE
handle prerelease gems fine

### ISSUE THREAD

**Issue by atmos** [wycats/bundler#19]
We have a webrat-0.4.4.racktest release we use internally while waiting for a new version of the gem to be released.  When specifying the version above it fetches and installs webrat-0.4.4 instead of our prerelease version.  If I just use gem install -i vendor/gems -v=0.4.4.racktest it behaves as expected.

**Comment by wycats** [comment]
I believe that this is fixed in rubygems 1.3.5. Could you confirm?
