### ISSUE TITLE
rake install broken

### ISSUE THREAD

**Issue by brynary** [wycats/bundler#20]
<pre>
$ rake install
(in /Users/bhelmkamp/p/bundler)
mkdir -p pkg
WARNING:  no rubyforge_project specified
WARNING:  no summary specified
  Successfully built RubyGem
  Name: bundler
  Version: 0.0.1
  File: bundler-0.0.1.gem
mv bundler-0.0.1.gem pkg/bundler-0.0.1.gem
rake aborted!
uninitialized constant GEM
/Users/bhelmkamp/p/bundler/Rakefile:44
(See full trace by running task with --trace)
</pre>

**Comment by sr** [comment]
http://github.com/wycats/bundler/issues#issue/17 has a patch

**Comment by wycats** [comment]
This should be fixed. The patch has been applied.
