### ISSUE TITLE
There is a dependency on rspec

### ISSUE THREAD

**Issue by TheNicholasNick** [wycats/bundler#22]
If you don't have rspec installed you can't run 

```
rake install
```

as it can't find:
    'spec/rake/spectask'

This only came up for me because all my projects are bundled therefore there isn't much installed when i go gem list. only rake, thor & defunkt-github (dependencies)

**Comment by carllerche** [comment]
We'll cut a gem soon so that it can be installed without running rake

**Comment by TheNicholasNick** [comment]
nice :)
