### ISSUE TITLE
Generated executables should use relative paths to vendored gems

### ISSUE THREAD

**Issue by danielsdeleo** [wycats/bundler#24]
Currently, bundler creates code like this in the bin/ directory:

```
require "/full/path/to/vendor/gems/environments/default"
load "/full/path/to/vendor/gems/gems/chef-0.7.4/bin/chef-client"
```

This means that the bundle can't be used on another system unless it's placed in an identical directory structure. bundler should instead determine the correct paths at runtime using `File.dirname(__FILE__)` or some similar mechanism, i.e.:

```
require File.dirname(__FILE__) + "/../vendor/gems/environments/default"
load File.dirname(__FILE__) + "/../vendor/gems/gems/chef-0.7.4/bin/chef-client"
```

**Comment by atmos** [comment]
Definitely makes sense.

**Comment by KieranP** [comment]
As, when I used 'gem install piston' for ruby gems, the bin file it generated made its way through bundler, and when using Ruby Enterprise Edition, gems/environments/default  doesn't exist, so all gems I've installed since trying bundler are not working if they have executables, and have to be reinstalled with bundler removed. Should it be overiding the gem install command?

**Comment by atmos** [comment]
Kieran, I believe this has been resolved in 0.3.1.  Can you test on your system?

**Comment by KieranP** [comment]
I had 0.3.1 installed when I tried to install piston.

**Comment by krisr** [comment]
I'm seeing this in 0.3.2. +1 on correcting this. It would be nice to actually have some command to regenerate the files in bin so as to also account for the correct path to ruby on different systems.

**Comment by carllerche** [comment]
Ok, this should be on master. Could you guys please try it out?

**Comment by KieranP** [comment]
Yep, awesome. Bundler is no longer messing with the bin files rubygems installs. Thanks.

**Comment by danielsdeleo** [comment]
Epic Win! OS X was frustrating my workaround attempts by putting UNIXy dirs under /private/. This is going to rule for lightweight Chef installs. Thanks!
