### ISSUE TITLE
Create minimal rubygems marshalling format

### ISSUE THREAD

**Issue by wycats** [wycats/bundler#30]
Submit a patch to Rubygems with a minimal marshalling format that can use the incremental updater and will satisfy bundler's needs with minimal download cost.

**Comment by brentd** [comment]
Not sure what version actually introduced it, but rubygems' specs.4.8.gz seems to be enough to satisfy bundler at the moment. It includes the gem name, version, and platform.

See my fork at http://github.com/brentd/bundler/ for an implementation using that format.

My implementation may be a bit dangerous - it goes out and fetches the full specification if anything other than those three attributes are needed. So if something more is eventually needed for the resolver to find gems, it'll hit the gem source for every specification - obviously a fail. For now though, it works nicely and gem source updates are much faster.

**Comment by carllerche** [comment]
I applied the patch. If it doesn't seem to work, we'll revisit this.
