### ISSUE TITLE
suggested setup for passenger deployment

### ISSUE THREAD

**Issue by atmos** [wycats/bundler#31]
When run under passenger there is a gem environment established before your application is actually run.  What's the plan for passenger rack apps?

**Comment by atmos** [comment]
This is functional in a variety of apps under passenger.

**Comment by carllerche** [comment]
Are you not able to create a ruby  wrapper script for passenger? That is how you pass in extra options as far as I know. Let me know if this doesn't work.

**Comment by mislav** [comment]
I'm running a Sinatra app with Passenger and Bundler without extra setup. Sure, rack have been loaded from rubygems, but at least other things aren't. I'm not sure if you can just happily bundle any version of rack you want and force that onto Passenger—historically it has been known to be tightly coupled with a specific version.
