### ISSUE TITLE
After changing version number, wrong package install is attempted

### ISSUE THREAD

**Issue by brynary** [wycats/bundler#32]
I originally had a dependency declared on memcached 0.11. Since that was causing a Gem::InstallError, I changed the dependency to memcached 0.14, re-ran the bundler, and got this:

<pre>
$ gem bundle
Calculating dependencies...
Updating source: http://gems.rubyforge.org
Downloading memcached-0.14.gem
Installing memcached-0.11.gem
ERROR:  While executing gem ... (Gem::InstallError)
    memcached requires RubyGems version = 1.2
</pre>

It downloaded the right version, but then tried to install the old one. rm -fr-ing my bundle directory fixed it.

**Comment by atmos** [comment]
0.3.1 was less buggy for me, is it still happening?

**Comment by carllerche** [comment]
This is resolved on master and will be released with 0.4
