### ISSUE TITLE
Need to be able to redeploy gems from gem cache.  

### ISSUE THREAD

**Issue by adelcambre** [wycats/bundler#35]
No network dependency at deploy time.

**Comment by mloughran** [comment]
+1

gem bundle should simply extract cache files if they satisfy the dependencies in the Gemfile.

Previously (sometime before 0.5) this seemed to be the behaviour.

Now, it deletes cache files unless a corresponding spec file exists. However if both the cache and spec file exists for a gem nothing is extracted. Either this is a bug or I'm missing something.

**Comment by brentd** [comment]
I'm able to redeploy gems from the cache just fine if cache is the only directory in my bundle_path.

There is indeed a network dependency, though - the sources are updated needlessly when all dependencies are met by the cache, as noted in Issue 37.

**Comment by carllerche** [comment]
on master yo... options: --cache and --cached
