### ISSUE TITLE
Should be able to have a .gem directory source type

### ISSUE THREAD

**Issue by paul** [wycats/bundler#36]
For example, tokyotyrant includes a .gemspec, but isn't on github or git or rubygems. It would be nice if I could build the rubygem myself, and copy the resulting pkg/tokyotyrant.gem into myapp/vendor/gems/cache, update the Gemfile, and have it able to be deployed without attempting to locate it on rubyforge.

**Comment by carlhuda** [comment]
It should be possible to have a source type that pulls from a directory of .gem files

**Comment by carllerche** [comment]
You can copy a gem to the bundler's cache by using the --cache option.
