### ISSUE TITLE
Tries to update gem sources, even if all gems are in cache

### ISSUE THREAD

**Issue by paul** [wycats/bundler#37]
The gems are all in the cache, but it insists on updating sources and re-downloading all gems. This is a regression, it did the right thing in 0.3.2.

To reproduce: 

```
% gem bundle
Calculating dependencies...
Updating source: http://gems.rubyforge.org
Updating source: file:/home/rando/development/gems
Downloading addressable-2.1.0.gem
...
% rm -rf vendor/gems/specifications
% gem bundle
Calculating dependencies...
Updating source: http://gems.rubyforge.org
```

**Comment by paul** [comment]
After some diggining, it appears that Repository#install and #fetch doesn't bother to check and see if the gems are already in the cache before attempting to fetch them.

**Comment by daveyeu** [comment]
Having the same beef, I took a crack at it here -- http://github.com/daveyeu/bundler/commit/ee572a93a91105d1bb63651049d16fc7b00abf19

**Comment by carllerche** [comment]
On master, there is a --cached option that will only use the cached gems.
