### ISSUE TITLE
Doesn't work with Ruby 1.9

### ISSUE THREAD

**Issue by brentd** [wycats/bundler#38]
```
% ruby -v
ruby 1.9.1p243 (2009-07-16 revision 24175) [i386-darwin10.0.0]
% gem -v
1.3.5
% gem install bundler
% mkdir myproject
% cd myproject
% echo "gem 'rails'" > Gemfile
% gem bundle
Calculating dependencies...
ERROR:  While executing gem ... (TypeError)
    can't convert Pathname into String
```

:(

Cloned the repo and ran the specs w/ 1.9 as well -- 88 failures.
For now maybe we can at least note in the README that bundler isn't compatible with Ruby 1.9 atm?

**Comment by radar** [comment]
I too get this error when following these steps.

**Comment by radar** [comment]
I have fixed this on my branch.

**Comment by carllerche** [comment]
This is fixed on master. There is only 1 failing spec for 1.9: disabling system gems. I'm not sure how to fix this as of yet.

**Comment by yury** [comment]
Just installed from HEAD and get same error.
bundler version 0.7.0.pre

<pre>
yury$ gem bundle
ERROR:  While executing gem ... (TypeError)
    can't convert Pathname into String
</pre>


<pre>
ruby -v
ruby 1.9.1p243 (2009-07-16 revision 24175) [x86_64-darwin10.0.0]
</pre>

**Comment by yury** [comment]
fixed here http://github.com/yury/bundler/commit/8a6458eb5d9a0e12998a2348fabc82693d046674
