### ISSUE TITLE
Re-building bundled gems with native extensions after deploy

### ISSUE THREAD

**Issue by brentd** [wycats/bundler#39]
How are bundled gems with native extensions handled after deploy?

I asked wycats this question on #carlhuda, and he indicated that all that would need to be done is `gem bundle` on the remote server, and any bundled gems with extensions would be compiled (provided that build artifacts were properly ignored from source control and such).

Maybe I'm just doin' it wrong, but I didn't see this behavior when I tried a test deploy. Here's a shell session that hopefully demonstrates:

http://gist.github.com/181460

**Comment by brentd** [comment]
New notes in the README have clarified this for me - specifically the bit that tells you to gitignore everything but vendor/gems/cache. This does force the gems to be re-installed when running `gem bundle` with only vendor/gems/cache present.

**Comment by carllerche** [comment]
This should be better on master with --cached and --cache options.
