### ISSUE TITLE
Cross-platform deployment unsupported

### ISSUE THREAD

**Issue by kobbler** [wycats/bundler#43]
I develop on Windows and deploy to Unix so gems that compile to platform-specific versions upon download to Windows are not appropriate for deployment to the remote Unix platform. It would be nice if Bundler had a solution for this.

**Comment by carllerche** [comment]
The solution is to NOT copy vendor/gems/gems over with your deployment. Only add vendor/gems/cache to your repository. Then, you can do gem bundle --cached and it will expand the gems on the new system, this includes compiling again.

**Comment by ognen** [comment]
Hmm, this might not be the ideal solution. 

Very often (in my company especially) systems in the DMZ are very "thin" and operators _do not_ like to have compilers installed on them (security risk).

It would be great if there is a way to bundle native gems too. Can pre-compiled gems live in the cache?
