### ISSUE TITLE
Eliminate warnings

### ISSUE THREAD

**Issue by wycats** [wycats/bundler#45]

**Comment by jeremy** [comment]
silence some warnings: http://github.com/jeremy/bundler/commit/6cbf142165e09065167e8778a0647a743744b473

**Comment by jeremy** [comment]
show warnings when running specs: http://github.com/jeremy/bundler/commit/552a1c5222f6b9afc0e4d9e84e9878a64120a84b

**Comment by carllerche** [comment]
This has been applied
