### ISSUE TITLE
Pre-release gems should not be installed by default

### ISSUE THREAD

**Issue by halorgium** [wycats/bundler#47]
By default, rubygems does not install pre-release gems. 
Perhaps if the dep is pre-release it should install the pre-release gem.

**Comment by carllerche** [comment]
I added some logic for this. It isn't perfect in some crazy cases, but it should hopefully be fine.

**Comment by chriseppstein** [comment]
How do we specify that we **do** want to use pre-release gems?

**Comment by halorgium** [comment]
If you specify an "=1.2.pre" version, it'll install it.
