### ISSUE TITLE
local gem cache directory

### ISSUE THREAD

**Issue by benburkert** [wycats/bundler#48]
I would like to use the bundler with local gems that I manage manually. Right now, it is possible to accomplish this with the :vendored_at option, but that requires more than just placing the gem file in a directory, and adding a :cached_at option or something. Please make this possible and not suck.

**Comment by halorgium** [comment]
Why not use a file-based gem source?
Check out the tests for some examples.

**Comment by brentd** [comment]
+1 for this. Maintaining a local gem repository is possible, but requires, well, maintaining it with `gem generate_index` and such. Not really ideal.

**Comment by carllerche** [comment]
Available on master.
