### ISSUE TITLE
:require_as => nil not being recognized

### ISSUE THREAD

**Issue by merbjedi** [wycats/bundler#59]
I have a gem (vlad-merb) that I need to bundle in a project, however I don't want to run a require on it. 

Traditionally I would have done something like this:

```
gem "vlad", :require_as => nil
gem 'vlad-git', :require_as => nil
gem 'vlad-merb', :require_as => nil
```

However, when it runs Bundler::Environment.load, i see the error

```
no such file to load -- vlad-git
/opt/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
/opt/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
/Users/jc/Merb/testapp/gems/gems/bundler-0.6.0/lib/bundler/dependency.rb:40:in `require_env'
/Users/jc/Merb/testapp/gems/gems/bundler-0.6.0/lib/bundler/dependency.rb:39:in `each'
/Users/jc/Merb/testapp/gems/gems/bundler-0.6.0/lib/bundler/dependency.rb:39:in `require_env'
/Users/jc/Merb/testapp/gems/gems/bundler-0.6.0/lib/bundler/environment.rb:114:in `require_env'
/Users/jc/Merb/testapp/gems/gems/bundler-0.6.0/lib/bundler/environment.rb:114:in `each'
/Users/jc/Merb/testapp/gems/gems/bundler-0.6.0/lib/bundler/environment.rb:114:in `require_env'
```

I traced the issue to lib/bundler/dependency.rb, where @require_as = Array(options["require_as"] || name)

Ideally, we should check for the existance of the ["require_as"] key, and only then default to name. If I set to nil, it shouldn't perform the require at all.

**Comment by merbjedi** [comment]
Fix provided here: 
http://github.com/merbjedi/bundler/commit/b1163b03ae3b360c10bbd8da6f341bfcf2f43716

Please review and merge if possible

**Comment by carllerche** [comment]
This is fixed in that if you dont' specify a require and the gem does not have a default require file, no exception will be raised.

If you absolutely don't want the gem to be required ever, use :only => :bundle

**Comment by merbjedi** [comment]
works for me. thanks!

**Comment by merbjedi** [comment]
Uggh, ran into this issue again.. and it took a while to find this thread again with the :only => :bundle. 

Is there a huge opposition to just allowing :require_as => nil. It seemed like good syntax with the merb bundler. And its an easy fix

**Comment by richievos** [comment]
Related duplicate (with my comments): http://github.com/wycats/bundler/issues/closed/#issue/126
