### ISSUE TITLE
using branch with rails git does not work or is it not meant to be done this way?

### ISSUE THREAD

**Issue by ghost** [wycats/bundler#62]
gem "rails", "2.3.4", :git => "git://github.com/rails/rails.git", :branch => "2-3-stable"

no such file to load -- initializer (LoadError) from boot.rb

its setting the load path to the dir directory; btw

**Comment by carllerche** [comment]
Sadely, for it to work with a git repo, there needs to be gemspecs in the repo which only rails master has. 0.7.0 will have better features for dealing with repositories that lack gemspecs.

**Comment by ssoroka** [comment]
It'd be awesome if you could specify any commit SHA and bundler would build it.

**Comment by carllerche** [comment]
It should be better now on 0.7.0... but documentation is lacking still...
