### ISSUE TITLE
Minor Doc Issue in README (with .gitignore)

### ISSUE THREAD

**Issue by merbjedi** [wycats/bundler#63]
The .gitignore you list causes some problems that I think might be dangerous if people start using it.

```
vendor/gems/
!vendor/gems/cache/
```

In this case, it'll only update your gems/cache folder if you explicitly call git add on it. Had it running like this until it a deployment broke by accident (since I forgot to run the git add call after gems were later updated in the cache). 

I ended up changing it to:

```
vendor/gems/gems/*
vendor/gems/specifications/*
vendor/gems/environment.rb
```

This might be a safer recommendation to people.

**Comment by merbjedi** [comment]
Here's the quick patch:
http://github.com/merbjedi/bundler/commit/8a9057edb6875ea320b6c9b9ebdddb02664faa90

**Comment by lapluviosilla** [comment]
Actually the correct syntax would be:

```
vendor/gems/*
!vendor/gems/cache
```

Try it for yourself and see that git will no longer ignore the cache dir this way.
