### ISSUE TITLE
undefined local variable or method `filename' for Bundler::Environment:Class

### ISSUE THREAD

**Issue by carllerche** [wycats/bundler#66]
command: gem bundle --cached -m /path/to/Gemfile

ERROR:  While executing gem ... (NameError)
    undefined local variable or method `filename' for Bundler::Environment:Class
    /var/lib/gems/1.8/gems/bundler-0.6.0/lib/bundler/environment.rb:17:in`load'
    /var/lib/gems/1.8/gems/bundler-0.6.0/lib/bundler/cli.rb:32:in `initialize'
    /var/lib/gems/1.8/gems/bundler-0.6.0/lib/bundler/cli.rb:6:in`new'
    /var/lib/gems/1.8/gems/bundler-0.6.0/lib/bundler/cli.rb:6:in `run'
    /var/lib/gems/1.8/gems/bundler-0.6.0/lib/bundler/commands/bundle_command.rb:51:in`execute'
    /usr/lib/ruby/1.8/rubygems/command.rb:257:in `invoke'
    /usr/lib/ruby/1.8/rubygems/command_manager.rb:132:in`process_args'
    /usr/lib/ruby/1.8/rubygems/command_manager.rb:102:in `run'
    /usr/lib/ruby/1.8/rubygems/gem_runner.rb:58:in`run'
    /usr/bin/gem:21

**Comment by wycats** [comment]
Closed by 8aed1a4a1f99c9b0e5da522624dfb54865923c91 (undefined local variable or method `filename' for Bundler::Environment:Class)
