### ISSUE TITLE
Add support for bootstrapping bundler

### ISSUE THREAD

**Issue by thewoolleyman** [wycats/bundler#68]
This is for CruiseControl.rb.  We want to vendor everything, so people can just checkout and run.  However, we need to use the native SystemTimer gem to fix [a bug](https://cruisecontrolrb.lighthouseapp.com/projects/9150/tickets/229-sometimes-git-hangs#ticket-229-14)

I attempted to automatically run the bundle command from preinitializer.rb, but that didn't work.  Details below:

preinitializer.rb:

<pre>
require "#{RAILS_ROOT}/vendor/gems/gems/bundler-0.6.0/lib/bundler.rb"
Bundler::CLI.run('bundle')
require "#{RAILS_ROOT}/vendor/gems/environment"
</pre>

Gemfile:

<pre>
# http://github.com/wycats/bundler
gem "bundler"
gem "SystemTimer"
</pre>

Simulate a new box environment (everything but native SystemTimer install checked in):
<pre>
$ gem bundle
$ rm -rf vendor/gems/gems/SystemTimer-1.1.1/
$ script/console

> > puts $:.grep(/SystemTimer/) # Note it got added twice
> > /Users/woolley/workspace/cruisecontrol.rb/vendor/gems/gems/SystemTimer-1.1.1/lib
> > /Users/woolley/workspace/cruisecontrol.rb/vendor/gems/gems/SystemTimer-1.1.1/bin
> > /Users/woolley/workspace/cruisecontrol.rb/vendor/gems/gems/SystemTimer-1.1.1/lib
> > /Users/woolley/workspace/cruisecontrol.rb/vendor/gems/gems/SystemTimer-1.1.1/bin
> > require 'system_timer'
> > MissingSourceFile: no such file to load -- system_timer
> > $ ls vendor/gems/gems # Of course it could not be loaded, it isn't there...
> > bundler-0.6.0

**Comment by carllerche** [comment]
I'm going to close this for now assuming removing the gemspec works.
