### ISSUE TITLE
Bundler does not use correct gem version when using system gems.

### ISSUE THREAD

**Issue by ojak** [wycats/bundler#70]
Bundler will only honor gem versions if running from local gems (e.g. bin/merb).  If system gems are used, only the latest version of gem is activated.

**Comment by carllerche** [comment]
I'm confused by this ticket. How do you use the system gems? The only way to use the bundler is by using bin/merb.

**Comment by carllerche** [comment]
It might be that this is simply a merb issue and not a bundler issue. If so, please post the ticket on the merb bug tracker.
