### ISSUE TITLE
Add flag to allow a forced "gem bundle --cached"

### ISSUE THREAD

**Issue by merbjedi** [wycats/bundler#73]
When using rvm with a bundled app, its very difficult to switch between ruby versions since the bundler doesn't recognize the ruby version switch, and my app throws segmentation faults when it tries to run the native gems built on a different ruby platform. I have to manually delete my expanded gems directories, and then run gem bundle --cached

I propose a flag to allow a forced overwrite so I can easily rebundle my gems when I switch ruby versions.

```
gem bundle --cached --force
```

I'm sure there's a slicker way to handle multiple ruby versions within the bundler, but this flag would help easy the pain in the short term.

**Comment by carlhuda** [comment]
We're going to add multiruby support

**Comment by carlhuda** [comment]
We're going to be adding support for multi ruby
