### ISSUE TITLE
Bundler.require_env where env is cucumber included modules just not happening

### ISSUE THREAD

**Issue by ghost** [wycats/bundler#82]
running under rails and using cucumber for instance;

any gem that I have that say includes a module into ActionController for example will not be applied; under the cucumber env; where I have the Bundler.require_env in the env cucumber file;

its just a mystery;

**Comment by carllerche** [comment]
That seems quite bizarre. I'm not able to reproduce. If you can figure out how to reproduce or write a failing spec, please reopen the ticket.
