### ISSUE TITLE
per environment build options

### ISSUE THREAD

**Issue by joshsusser** [wycats/bundler#84]
I think it's better to separate build options into different files. I'd really like to be able to check in options for deploying to demo and especially production to ease spinning up new slices in the cloud, for example. Development might need more tweaking, but production should be a known quantity. So how about having per environment config files, either a .yml for real config, or .yml.example (or whatever) for an exemplar that is meant to be copied and modified locally?

```
build_options/
  development.yml.example
  production.yml
```

**Comment by wycats** [comment]
Since the API is to use --build-options, you can just do --build-options production.yml
