### ISSUE TITLE
Failure under jruby

### ISSUE THREAD

**Issue by pivotal-legacy** [wycats/bundler#85]
Using this bundler file in a new rails app under Jruby, we got the following errors.

gem "rails", "2.3.4"
gem "rack", "1.0.1"
gem "warbler", "0.9.14"
gem "jruby-jars", "1.3.1"

bundle_path "bundler/gems"
bin_path "bundler/executables"

ERRORS:

ajo:execwar pivotal$ gem bundle
Calculating dependencies...
Updating source: http://gems.rubyforge.org
Downloading actionmailer-2.3.4.gem
Downloading actionpack-2.3.4.gem
Downloading activerecord-2.3.4.gem
Downloading activeresource-2.3.4.gem
Downloading activesupport-2.3.4.gem
Downloading jruby-jars-1.3.1.gem
Downloading rack-1.0.1.gem
Downloading rails-2.3.4.gem
Downloading rake-0.8.7.gem
Downloading warbler-0.9.14.gem
Installing rails (2.3.4)
ERROR:  While executing gem ... (TypeError)
    wrong argument type Pathname (expected String)
ajo:execwar pivotal$ ls bundler/gems/
cache/          doc/            gems/           specifications/ 
ajo:execwar pivotal$ gem bundle
Calculating dependencies...
Updating source: http://gems.rubyforge.org
Installing rack (1.0.1)
ERROR:  While executing gem ... (TypeError)
    wrong argument type Pathname (expected String)
ajo:execwar pivotal$ gem bundle
Calculating dependencies...
Updating source: http://gems.rubyforge.org
Installing warbler (0.9.14)
ERROR:  While executing gem ... (TypeError)
    wrong argument type Pathname (expected String)

**Comment by wycats** [comment]
The 1.9 fixes should have fixed this
