### ISSUE TITLE
Inner class <context>.gem doesn't work properly in Bundler.require_env.

### ISSUE THREAD

**Issue by zliang-min** [wycats/bundler#86]
I'm using bundler 0.6.0.
In vendor/gems/environment.rb, line 50, it's:
opt = args.last || {}

It should be:
opt = args.last.is_a?(Hash) && args.last || {}

Or "gem "mylib", "1.2.3" won't work correctly.

**Comment by zliang-min** [comment]
Sorry, I was mistaken. It's not necessary in line 50.
But it's the 15th line inside the Bundler.require_env method.

**Comment by shanna** [comment]
I can confirm this. Line 62 in the environment template assumes the last argument will be a hash. 
http://github.com/wycats/bundler/blob/master/lib/bundler/templates/environment.erb#L62

Fix but I can't get the tests to run in Ruby 1.9 so I didn't add a new test for this.
http://github.com/shanna/bundler/commit/f628df573ae85f41a5b422871ca88a8369e2b57f

**Comment by wycats** [comment]
The tests should run in 1.9 now; would you mind submitting a test?
