### ISSUE TITLE
Bundler without GCC

### ISSUE THREAD

**Issue by merbjedi** [wycats/bundler#87]
My client's sysadmin nixed my plans to move the project over to bundler. The issue, we aren't allowed to have any developer tools on the production boxes (gcc, etc). And rubygems requires compilation of many gems. He's got a crazy setup where he converts all his gems to RPM binaries and installs that. 

I was thinking maybe bundler could take a stab and handling this. So some way to include precompiled binaries within the project (using platform target specifiers).

**Comment by carllerche** [comment]
What if we port gcc to pure ruby and bundle it in the bundler?

**Comment by tenderlove** [comment]
You can build pre-compiled gems for your platform.  Those should work with bundler out of the box.

See [rake-compiler](http://github.com/luislavena/rake-compiler) for how you can build a binary gem.

**Comment by merbjedi** [comment]
Great tip. I'll give that a try. Thanks Aaron

**Comment by carllerche** [comment]
Cool, hopefully it works out
