### ISSUE TITLE
Bundler issue with Ruby version 1.9.1

### ISSUE THREAD

**Issue by wdperson** [wycats/bundler#89]
Hello,

I am using Ruby 1.9.1 and cloned the repo (no prior Bundler versions installed).  I did a rake install in the bundler directory and it installs without any errors.  After doing this the gem command is unusable (can't do gem -v, gem list, etc.).  I get the following error:

bundler-0.7.0.pre/lib/rubygems_plugin.rb:2:in `require': no such file to load -- bundler/commands/bundle_command (LoadError)

thanks

**Comment by wdperson** [comment]
Hello,

I got this figured out after a few hours of working on this.  I was using rvm and the gem was installed in:

~/.rvm/ruby-1.9.1-p243/lib/ruby/gems/1.9.1

This was not allowing bundler to find the gem at all.  Copying over the contents of:
bundler-0.6.0.gemspec to ~/.gem/ruby/1.9.1/specifications/ and bundler-0.6.0/ to ~/.gem/ruby/1.9.1/gems/ fixed this issue.  

Mike Riley

**Comment by somebee** [comment]
I fixed this issue to by just doing sudo rake install instead (as one would expect), but I still cannot get bundler from master to work on 1.9.1

$ gem bundle
ERROR:  While executing gem ... (TypeError)
    can't convert Pathname into String

Did you experience this along the way?

**Comment by carllerche** [comment]
This should be fixed on master
