### ISSUE TITLE
Equivalent of :lib => false

### ISSUE THREAD

**Issue by dstrelau** [wycats/bundler#91]
Right now, there is no easy way to tell bundler "hey, I want this gem around and available, but I don't want you to require it for me all the time." The work-around is to call `:require_as => []`, but this is ugly and it only works due to knowing how the internals of `require_as` work.

It would be nice to see an easy way to specify this; maybe `:require => false` or `:gem_only => true`?

**Comment by carllerche** [comment]
gem "foo", :only => :bundle is what I do.

**Comment by dstrelau** [comment]
Hmm, that's smart! Why didn't I think of that?

It might be nice to mention this in the documentation somewhere…for slow people like me.

**Comment by richievos** [comment]
Related duplicate (with my comments): http://github.com/wycats/bundler/issues/closed/#issue/126
