### ISSUE TITLE
Not loading files in path related to location of gemspec?

### ISSUE THREAD

**Issue by somebee** [wycats/bundler#94]
When I try to bundle data_objects from git://github.com/datamapper/do.git I run into this problem:

git "git://github.com/datamapper/do.git" do
  gem "data_objects", :path => "data_objects"
end

/usr/local/ruby-1.9.1-p243/lib/ruby/gems/1.9.1/gems/bundler-0.7.0.pre/lib/bundler/source.rb:217:in `eval': no such file to load -- lib/data_objects/version (LoadError)
    from (eval):1:in`block in locate_gemspecs'
    from /usr/local/ruby-1.9.1-p243/lib/ruby/gems/1.9.1/gems/bundler-0.7.0.pre/lib/bundler/source.rb:217:in `eval'
    from /usr/local/ruby-1.9.1-p243/lib/ruby/gems/1.9.1/gems/bundler-0.7.0.pre/lib/bundler/source.rb:217:in`block in locate_gemspecs'
    from /usr/local/ruby-1.9.1-p243/lib/ruby/gems/1.9.1/gems/bundler-0.7.0.pre/lib/bundler/source.rb:215:in `each'
    from /usr/local/ruby-1.9.1-p243/lib/ruby/gems/1.9.1/gems/bundler-0.7.0.pre/lib/bundler/source.rb:215:in`inject'
    from /usr/local/ruby-1.9.1-p243/lib/ruby/gems/1.9.1/gems/bundler-0.7.0.pre/lib/bundler/source.rb:215:in `locate_gemspecs'
    from /usr/local/ruby-1.9.1-p243/lib/ruby/gems/1.9.1/gems/bundler-0.7.0.pre/lib/bundler/source.rb:200:in`gems'
    from /usr/local/ruby-1.9.1-p243/lib/ruby/gems/1.9.1/gems/bundler-0.7.0.pre/lib/bundler/source.rb:319:in `gems'
    from /usr/local/ruby-1.9.1-p243/lib/ruby/gems/1.9.1/gems/bundler-0.7.0.pre/lib/bundler/resolver.rb:78:in`block in initialize'
    from /usr/local/ruby-1.9.1-p243/lib/ruby/gems/1.9.1/gems/bundler-0.7.0.pre/lib/bundler/resolver.rb:77:in `each'
    from /usr/local/ruby-1.9.1-p243/lib/ruby/gems/1.9.1/gems/bundler-0.7.0.pre/lib/bundler/resolver.rb:77:in`initialize'
    from /usr/local/ruby-1.9.1-p243/lib/ruby/gems/1.9.1/gems/bundler-0.7.0.pre/lib/bundler/resolver.rb:40:in `new'
    from /usr/local/ruby-1.9.1-p243/lib/ruby/gems/1.9.1/gems/bundler-0.7.0.pre/lib/bundler/resolver.rb:40:in`resolve'
    from /usr/local/ruby-1.9.1-p243/lib/ruby/gems/1.9.1/gems/bundler-0.7.0.pre/lib/bundler/repository.rb:40:in `install'
    from /usr/local/ruby-1.9.1-p243/lib/ruby/gems/1.9.1/gems/bundler-0.7.0.pre/lib/bundler/environment.rb:51:in`install'
    from /usr/local/ruby-1.9.1-p243/lib/ruby/gems/1.9.1/gems/bundler-0.7.0.pre/lib/bundler/cli.rb:39:in `bundle'
    from /usr/local/ruby-1.9.1-p243/lib/ruby/gems/1.9.1/gems/bundler-0.7.0.pre/lib/bundler/cli.rb:65:in`run'
    from /usr/local/ruby-1.9.1-p243/lib/ruby/gems/1.9.1/gems/bundler-0.7.0.pre/lib/bundler/cli.rb:6:in `run'
    from /usr/local/ruby-1.9.1-p243/lib/ruby/gems/1.9.1/gems/bundler-0.7.0.pre/lib/bundler/commands/bundle_command.rb:63:in`execute'
    from /usr/local/ruby-1.9.1-p243/lib/ruby/gems/1.9.1/gems/rubygems-update-1.3.5/lib/rubygems/command.rb:257:in `invoke'
    from /usr/local/ruby-1.9.1-p243/lib/ruby/gems/1.9.1/gems/rubygems-update-1.3.5/lib/rubygems/command_manager.rb:132:in`process_args'
    from /usr/local/ruby-1.9.1-p243/lib/ruby/gems/1.9.1/gems/rubygems-update-1.3.5/lib/rubygems/command_manager.rb:102:in `run'
    from /usr/local/ruby-1.9.1-p243/lib/ruby/gems/1.9.1/gems/rubygems-update-1.3.5/lib/rubygems/gem_runner.rb:58:in`run'
    from /usr/local/ruby/bin/gem:24:in `<main>'

It borks when loading the data_objects/data_objects.gemspec which tries to require:
require 'lib/data_objects/version'

This path is relative to the actual gemspec-file, not the root of the git-repository.

Am I misunderstanding how bundler should work, is this a bug with the format / conventions followed by the data_objects.gemspec, or is it a bug with bundler?

**Comment by carllerche** [comment]
This is a problem with the DO gemspec. It is not a valid gemspec (requires files). I have spoken with the DO maintainers about this and it will hopefully get fixed.
