### ISSUE TITLE
Error installing gems with a bin dir on jruby

### ISSUE THREAD

**Issue by devwout** [wycats/bundler#95]
ERROR:  While executing gem ... (TypeError)
    wrong argument type Pathname (expected String)

The problem is reproducable for any gem that wants to install binaries (rake, rails, ...)

The solution:

<pre>
diff --git a/lib/bundler/repository.rb b/lib/bundler/repository.rb
index 418ecbb..6333f6f 100644
--- a/lib/bundler/repository.rb
+++ b/lib/bundler/repository.rb
@@ -130,7 +130,7 @@ module Bundler
         installer = Gem::Installer.allocate
         installer.instance_eval do
           @spec     = spec
-          @bin_dir  = bin_dir
+          @bin_dir  = bin_dir.to_s
           @gem_dir  = path.join("gems", "#{spec.full_name}")
           @gem_home = path
           @wrappers = true
</pre>

The problem is jruby only accepts strings as argument of Dir.mkdir, while MRI will accept anything it can convert to a String. Bundler uses a Pathname object for the bin dir.

**Comment by rubiii** [comment]
would be nice to see this one fixed in bundler. but the problem was also fixed with jruby 1.4. take a look at: http://jira.codehaus.org/browse/JRUBY-4179
hope you're able to upgrade.

**Comment by devwout** [comment]
Thank you, guess that closes this issue.
