### ISSUE TITLE
Add Gem.dir method to support Sinatra

### ISSUE THREAD

**Issue by woodie** [wycats/bundler#98]
~/bundler_gems/environment.rb
    module Gem
      def self.dir; ENV['GEM_HOME']; end
      ...
    end

**Comment by sr** [comment]
The underlying issue here is that Sinatra tries to be clever about wheter RubyGems is loaded or not in order to clean up the backtrace. http://github.com/sinatra/sinatra/blob/master/lib/sinatra/base.rb#L616
Not sure how that should be fixed in Sinatra. Any idea?

**Comment by woodie** [comment]
For Rails 3 to work (with rubygems disabled) you may need these:
    def self.default_dir; ENV['GEM_HOME']; end
    def self.dir; ENV['GEM_HOME']; end
    def self.path; ENV['GEM_PATH']; end

**Comment by mislav** [comment]
Nothing wrong with what Sinatra does. I have added `Gem.dir` in mislav@146db30f1c05363c4cccd38092893c0850b278d5 and others in mislav@53f6e471db38572fd96121aeaebacc43d2f065dd

**Comment by woodie** [comment]
Cool, what version of bundler can I expect there? I need to stop patching on my end :
http://code.google.com/p/appengine-jruby/source/browse/appengine-tools/lib/appengine-tools/gem_bundler.rb

**Comment by carllerche** [comment]
The patches have been applied. They'll be released with whatever the next release is (patch level or minor, unsure yet, but it will be soon).
