### ISSUE TITLE
Allow me to force/override settings in Gemfile and set ruby platform

### ISSUE THREAD

**Issue by woodie** [wycats/bundler#99]
I want uses to have access to all the methods, but I need to override some:

```
:disable_system_gems => true
:disable_rubygems => true
:bundle_path => "my/custom/path"
```

Don't assume my current ruby ENV reports my target platform.
I'd need some way to tell bundler about the target platform: 

```
Gem.platforms = [Gem::Platform::RUBY, Gem::Platform.new('universal-java')]
```

**Comment by carllerche** [comment]
This will work with the multi ruby support coming soon

**Comment by woodie** [comment]
ok, cool. Let me know if I can contribute somehow.
